In [1]:
import numpy as np
import gll_library

In [2]:
ngll = 5
z, w = gll_library.zwgljd(ngll,0,0)
z, w

(array([-1.        , -0.65465367,  0.        ,  0.65465367,  1.        ]),
 array([0.1       , 0.54444444, 0.71111111, 0.54444444, 0.1       ]))

## derivative of Lagrange polynomials
$$\eqalign{
  & {N_i} = \prod\limits_{j = 0,j \ne i}^N {\left( {\xi _i^{GLL} - \xi _j^{GLL}} \right)}   \cr 
  & {\ell _i}\left( \xi  \right) = N_i^{ - 1}\prod\limits_{j = 0,j \ne i}^N {\left( {\xi  - \xi _j^{GLL}} \right)}   \cr 
  & {{\dot \ell }_i}\left( \xi  \right) = N_i^{ - 1}\sum\limits_{k \ne i} {\prod\limits_{m \ne i,k} {\left( {\xi  - \xi _m^{GLL}} \right)} }  \cr} $$

In [ ]:
def dLag_dzgll(ngll):
    """ derivative of Lagrange polynomials evaluated at n-point GLL nodes
    """
    z, w = gll_library.zwgljd(ngll,0,0)
    # dLag_i/dz(zj)
    dLag = np.zeros((ngll, ngll))
    ind = np.arange(ngll)
    for i in range(ngll):
        denumerator = np.prod((z[i] - z[ind != i]))
        for j in range(ngll):
            numerator = 0
            for k in range(ngll):
                if k == i: continue
                mask = (ind != i) & (ind != k)
                numerator += np.prod(z[j] - z[mask])
            dLag[i,j] = numerator/denumerator
    return dLag

In [20]:
dLag_dzgll(ngll)

array([[-5.00000000e+00, -1.24099025e+00,  3.75000000e-01,
        -2.59009747e-01,  5.00000000e-01],
       [ 6.75650249e+00,  2.26670534e-16, -1.33658458e+00,
         7.63762616e-01, -1.41016418e+00],
       [-2.66666667e+00,  1.74574312e+00, -1.29526020e-16,
        -1.74574312e+00,  2.66666667e+00],
       [ 1.41016418e+00, -7.63762616e-01,  1.33658458e+00,
         9.06682137e-16, -6.75650249e+00],
       [-5.00000000e-01,  2.59009747e-01, -3.75000000e-01,
         1.24099025e+00,  5.00000000e+00]])

In [12]:
gll_library.lagrange_deriv_gll(4,4, z)

5.0

In [21]:
for i in range(ngll):
    for j in range(ngll):
        print(gll_library.lagrange_deriv_gll(i,j, z))

-5.0
-1.2409902530309833
0.375
-0.2590097469690172
0.5
6.756502488724241
0.0
-1.336584577695453
0.7637626158259734
-1.4101641779424265
-2.6666666666666665
1.745743121887939
0.0
-1.7457431218879396
2.6666666666666665
1.4101641779424268
-0.7637626158259734
1.3365845776954532
0.0
-6.756502488724238
-0.5
0.25900974696901713
-0.375
1.2409902530309824
5.0


## GLL nodes and weights

Legendre polynomials given by Rodrigues' formula:
\begin{equation}
  P_n\,(\xi)
  \,=\,\frac{1}{2^n n!}\,\left(\frac{d}{dx}\right)^n\left({\xi}^2\,-\,1\right)^n
\end{equation}

The *Legendre polynomials* can also be calculated via recursion (Bonnet formula) such as:

\begin{split}
    P_0\,(\xi)
    \,&=\,1\\
    P_1\,(\xi)
    \,&=\,\xi\\
    P_n\,(\xi)
    \,&=\,\frac{(2n\,-\,1)\,\xi\, P_{n\,-\,1}\,(\xi)\,-\,(n\,-\,1)\,P_{n\,-\,2}\,(\xi)}{n}\qquad n \geq 2
\end{split}